from .connection import conectar_duckdb
from .loader import registrar_csvs_como_vistas, verificar_vistas
from .inspector import (
    resumen_columnas, 
    distribucion_categoria, 
    info_tabla,
    dimensiones_tabla,
    tipos_datos,
    estadisticos_numericos,
    valores_constantes,
    porcentaje_nulos,
    analisis_inicial_completo,
    guardar_resultados_como_txt,
    skew_categorico,
    entropia_columna,
    columnas_booleanas,
    columnas_fecha_invalida,
    correlaciones_numericas,
     indice_variedad,
    # tasa_renovacion,
    desviacion_precio,
    proporcion_premium,
    densidad_categoria,
    # frecuencia_temporal,
    relacion_publicaciones_stock,
    ratio_nuevos_vs_reacondicionados,
    proporcion_precios_bajos
)

__all__ = [
    "conectar_duckdb",
    "registrar_csvs_como_vistas",
    "verificar_vistas",
    "resumen_columnas",
    "distribucion_categoria",
    "info_tabla",
    "dimensiones_tabla",
    "tipos_datos",
    "estadisticos_numericos",
    "valores_constantes",
    "porcentaje_nulos",
    "analisis_inicial_completo",
    "guardar_resultados_como_txt",
    "skew_categorico",
    "entropia_columna",
    "columnas_booleanas",
    "columnas_fecha_invalida",
    "correlaciones_numericas",
     "indice_variedad",
    # "tasa_renovacion",
    "desviacion_precio",
    "proporcion_premium",
    "densidad_categoria",
    # "frecuencia_temporal",
    "relacion_publicaciones_stock",
    "ratio_nuevos_vs_reacondicionados",
    "proporcion_precios_bajos"
]